name: dada2
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - _r-mutex=1.0.1
  - binutils_impl_linux-64=2.35
  - binutils_linux-64=2.35
  - bioconductor-biobase=2.48.0
  - bioconductor-biocgenerics=0.34.0
  - bioconductor-biocparallel=1.22.0
  - bioconductor-biostrings=2.56.0
  - bioconductor-dada2=1.16.0
  - bioconductor-delayedarray=0.14.0
  - bioconductor-genomeinfodb=1.24.0
  - bioconductor-genomeinfodbdata=1.2.4
  - bioconductor-genomicalignments=1.24.0
  - bioconductor-genomicranges=1.40.0
  - bioconductor-iranges=2.22.1
  - bioconductor-rhtslib=1.20.0
  - bioconductor-rsamtools=2.4.0
  - bioconductor-s4vectors=0.26.0
  - bioconductor-shortread=1.46.0
  - bioconductor-summarizedexperiment=1.18.1
  - bioconductor-xvector=0.28.0
  - bioconductor-zlibbioc=1.34.0
  - biom-format=2.1.10
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.16.1
  - ca-certificates=2020.12.5
  - cached-property=1.5.1
  - cairo=1.16.0
  - certifi=2020.12.5
  - click=7.1.2
  - curl=7.71.1
  - cutadapt=2.10
  - dnaio=0.4.2
  - fontconfig=2.13.1
  - freetype=2.10.4
  - fribidi=1.0.10
  - future=0.18.2
  - gcc_impl_linux-64=9.3.0
  - gcc_linux-64=9.3.0
  - gettext=0.19.8.1
  - gfortran_impl_linux-64=9.3.0
  - gfortran_linux-64=9.3.0
  - graphite2=1.3.13
  - gsl=2.6
  - gxx_impl_linux-64=9.3.0
  - gxx_linux-64=9.3.0
  - h5py=3.1.0
  - harfbuzz=2.7.2
  - hdf5=1.10.6
  - icu=67.1
  - jpeg=9d
  - kernel-headers_linux-64=2.6.32
  - krb5=1.17.1
  - ld_impl_linux-64=2.35
  - libblas=3.8.0
  - libcblas=3.8.0
  - libcurl=7.71.1
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.2.1
  - libgcc-devel_linux-64=9.3.0
  - libgcc-ng=9.3.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libglib=2.66.2
  - libgomp=9.3.0
  - libiconv=1.16
  - liblapack=3.8.0
  - libnghttp2=1.41.0
  - libopenblas=0.3.10
  - libpng=1.6.37
  - libssh2=1.9.0
  - libstdcxx-devel_linux-64=9.3.0
  - libstdcxx-ng=9.3.0
  - libtiff=4.1.0
  - libuuid=2.32.1
  - libwebp-base=1.1.0
  - libxcb=1.13
  - libxml2=2.9.10
  - lz4-c=1.9.2
  - make=4.3
  - ncurses=6.2
  - numpy=1.20.0
  - openjdk=10.0.2
  - openssl=1.1.1i
  - pandas=1.2.1
  - pango=1.42.4
  - parallel=20201122
  - pcre=8.44
  - pcre2=10.35
  - perl=5.32.0
  - pigz=2.3.4
  - pip=20.2.4
  - pixman=0.38.0
  - pthread-stubs=0.4
  - python=3.8.6
  - python-dateutil=2.8.1
  - python_abi=3.8
  - pytz=2021.1
  - r-askpass=1.1
  - r-assertthat=0.2.1
  - r-backports=1.1.10
  - r-base=4.0.3
  - r-bh=1.72.0_3
  - r-bitops=1.0_6
  - r-callr=3.5.1
  - r-cli=2.1.0
  - r-colorspace=1.4_1
  - r-covr=3.5.1
  - r-crayon=1.3.4
  - r-curl=4.3
  - r-desc=1.2.0
  - r-digest=0.6.27
  - r-ellipsis=0.3.1
  - r-evaluate=0.14
  - r-fansi=0.4.1
  - r-farver=2.0.3
  - r-formatr=1.7
  - r-futile.logger=1.4.3
  - r-futile.options=1.0.1
  - r-getopt=1.20.3
  - r-ggplot2=3.3.2
  - r-glue=1.4.2
  - r-gtable=0.3.0
  - r-highr=0.8
  - r-httr=1.4.2
  - r-hwriter=1.3.2
  - r-isoband=0.2.2
  - r-jpeg=0.1_8.1
  - r-jsonlite=1.7.1
  - r-knitr=1.30
  - r-labeling=0.4.2
  - r-lambda.r=1.2.4
  - r-lattice=0.20_41
  - r-latticeextra=0.6_29
  - r-lazyeval=0.2.2
  - r-lifecycle=0.2.0
  - r-magrittr=1.5
  - r-markdown=1.1
  - r-mass=7.3_53
  - r-matrix=1.2_18
  - r-matrixstats=0.57.0
  - r-mgcv=1.8_33
  - r-mime=0.9
  - r-munsell=0.5.0
  - r-nlme=3.1_150
  - r-openssl=1.4.3
  - r-optparse=1.6.6
  - r-pillar=1.4.6
  - r-pkgbuild=1.1.0
  - r-pkgconfig=2.0.3
  - r-pkgload=1.1.0
  - r-plyr=1.8.6
  - r-png=0.1_7
  - r-praise=1.0.0
  - r-prettyunits=1.1.1
  - r-processx=3.4.4
  - r-ps=1.4.0
  - r-r6=2.5.0
  - r-rcolorbrewer=1.1_2
  - r-rcpp=1.0.4.6
  - r-rcppparallel=5.0.2
  - r-rcurl=1.98_1.2
  - r-reshape2=1.4.4
  - r-rex=1.2.0
  - r-rlang=0.4.7
  - r-rprojroot=1.3_2
  - r-rstudioapi=0.11
  - r-scales=1.1.1
  - r-snow=0.4_3
  - r-stringi=1.5.3
  - r-stringr=1.4.0
  - r-sys=3.4
  - r-testthat=2.3.2
  - r-tibble=3.0.4
  - r-utf8=1.1.4
  - r-vctrs=0.3.4
  - r-viridislite=0.3.0
  - r-withr=2.3.0
  - r-xfun=0.19
  - r-yaml=2.2.1
  - r-zeallot=0.1.0
  - readline=8.0
  - scipy=1.6.0
  - sed=4.8
  - setuptools=49.6.0
  - six=1.15.0
  - sqlite=3.33.0
  - sysroot_linux-64=2.12
  - tk=8.6.10
  - tktable=2.10
  - trimmomatic=0.39
  - wheel=0.35.1
  - xopen=0.9.0
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
  - zstd=1.4.5
