name: qiime1
channels:
  - https://repo.anaconda.com/pkgs/free
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - backports=1.0
  - backports.functools_lru_cache=1.6.1
  - backports.shutil_get_terminal_size=1.0.0
  - biom-format=2.1.7
  - blas=1.0
  - burrito=0.9.1
  - burrito-fillings=0.1.1
  - ca-certificates=2020.12.5
  - cairo=1.12.18
  - certifi=2016.9.26
  - click=7.1.2
  - cogent=1.5.3
  - decorator=4.4.2
  - emperor=0.9.51
  - enum34=1.1.10
  - fontconfig=2.11.1
  - freetype=2.5.5
  - funcsigs=1.0.2
  - future=0.18.2
  - gdata=2.0.18
  - gettext=0.19.8.1
  - glib=2.58.3
  - h5py=2.7.1
  - hdf5=1.10.1
  - icu=68.1
  - ipython=5.8.0
  - ipython_genutils=0.2.0
  - ld_impl_linux-64=2.35.1
  - libffi=3.2.1
  - libgcc=7.2.0
  - libgcc-ng=9.3.0
  - libgfortran=3.0.0
  - libgfortran-ng=9.3.0
  - libgfortran5=9.3.0
  - libgomp=9.3.0
  - libiconv=1.16
  - libpng=1.6.17
  - libstdcxx-ng=9.3.0
  - libuuid=2.32.1
  - libxcb=1.13
  - libxml2=2.9.10
  - matplotlib=1.4.3
  - mkl=11.3.3
  - mock=2.0.0
  - mpi=1.0
  - mpi4py=3.0.3
  - mpich=3.4.1
  - mysql-connector-c=6.1.11
  - mysql-python=1.2.5
  - natsort=3.5.0
  - ncurses=6.2
  - nose=1.3.7
  - numpy=1.10.4
  - openssl=1.1.1i
  - pandas=0.22.0
  - pathlib2=2.3.5
  - pbr=5.5.1
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - pixman=0.32.6
  - prompt_toolkit=1.0.15
  - pthread-stubs=0.4
  - ptyprocess=0.7.0
  - py2cairo=1.10.0
  - pygments=2.2.0
  - pynast=1.2.2
  - pyparsing=2.0.3
  - pyqi=0.3.2
  - pyqt=4.11.4
  - python=2.7.15
  - python-dateutil=2.8.1
  - python_abi=2.7
  - pytz=2020.1
  - qcli=0.1.1
  - qiime=1.9.1
  - qiime-default-reference=0.1.3
  - qt=4.8.7
  - readline=8.0
  - scandir=1.10.0
  - scikit-bio=0.2.3
  - scipy=0.17.1
  - setuptools=36.4.0
  - simplegeneric=0.8.1
  - sip=4.18
  - six=1.15.0
  - sqlalchemy=1.3.5
  - sqlite=3.34.0
  - tk=8.6.10
  - traitlets=4.3.3
  - wcwidth=0.2.5
  - wheel=0.36.2
  - xorg-kbproto=1.0.7
  - xorg-libice=1.0.10
  - xorg-libsm=1.2.3
  - xorg-libx11=1.6.12
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xorg-libxext=1.3.4
  - xorg-libxrender=0.9.10
  - xorg-renderproto=0.11.1
  - xorg-xextproto=7.3.0
  - xorg-xproto=7.0.31
  - xz=5.2.5
  - zlib=1.2.11
